services:
  projects-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://projects-manager.api.leopeyronnet.fr/api
    container_name: projects-manager
    ports:
      - "3000:80"
    networks:
      - projects_manager_api_external
    restart: unless-stopped

networks:
  projects_manager_api_external:
    external: true